# Generated by Django 4.1.3 on 2022-12-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("user", models.CharField(default="anuj04", max_length=50)),
                ("article_id", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name_plural": "Likes",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("article_image", models.ImageField(upload_to="imgs/")),
                ("details", models.TextField(max_length=5000)),
                ("likes", models.BigIntegerField(default=0)),
                ("url", models.CharField(max_length=500)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News",
            },
        ),
    ]
